services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CONDUIT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONDUIT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONDUIT_POSTGRES_DB}
    ports:
      - ${CONDUIT_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5

  migrations:
    build:
      context: .
      target: migrations
    env_file:
      - .env
    environment:
      CONDUIT_POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  conduit:
    build:
      context: .
      target: runtime
    env_file:
      - .env
    environment:
      CONDUIT_POSTGRES_HOST: postgres
      CONDUIT_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0/api/v1/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5

  e2e-tests:
    image: postman/newman:alpine
    volumes:
      - "./tests/e2e:/etc/newman:ro"
    command:
      - run
      - --env-var
      - APIURL=http://conduit/api/v1
      - Conduit.postman_collection.json
    depends_on:
      conduit:
        condition: service_healthy
