version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CONDUIT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONDUIT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONDUIT_POSTGRES_DB}
    ports:
      - ${CONDUIT_POSTGRES_PORT}:5432
