name: Conduit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CONDUIT_POSTGRES_USER: test
  CONDUIT_POSTGRES_PASSWORD: test_password
  CONDUIT_POSTGRES_DB: test
  CONDUIT_POSTGRES_HOST: locahost
  CONDUIT_POSTGRES_PORT: 5432
  CONDUIT_SECRET_KEY: test_secret_key

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: "1.4.2"
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install --no-root
    - name: Check code formatting with Ruff
      run: ruff format --check
    - name: Lint with Ruff
      run: ruff check --output-format github
    - name: Check typing with Mypy
      run: mypy
    - name: Test with Pytest
      run: pytest ./tests/unit
